apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission-registry
webhooks:
  - name: io.ydzs.admission-registry
    rules:
      - apiGroups:   [""]
        apiVersions: ["v1"]
        operations:  ["CREATE"]
        resources:   ["pods"]
    clientConfig:
      service:
        namespace: default
        name: admission-registry
        path: "/validate"
      caBundle: ""
    admissionReviewVersions: ["v1"]
    sideEffects: None